<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKExUVzU\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKExUVzU/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKExUVzU.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKExUVzU\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKExUVzU\App_KernelProdContainer([
    'container.build_hash' => 'KExUVzU',
    'container.build_id' => '65f1d203',
    'container.build_time' => 1588599732,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKExUVzU');
