<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '1' => [[], ['_controller' => 'App\\Controller\\FirstLabController::index'], [], [['text', '/1']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], []],
    '2' => [[], ['_controller' => 'App\\Controller\\SecondLabController::index'], [], [['text', '/2']], [], []],
    'planet_search' => [[], ['_controller' => 'App\\Controller\\SecondLabController::search'], [], [['text', '/2/search']], [], []],
    '3' => [[], ['_controller' => 'App\\Controller\\ThirdLabController::index'], [], [['text', '/3']], [], []],
];
